name: Cron Commit

on:
  schedule:
    - cron: '0 7 * * *' # runs at 7 AM UTC every day
  workflow_dispatch: # allows manual trigger (optional)

jobs:
  cron-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update file or perform task
        run: |
          echo "Last run: $(date -u)" > last_run.txt

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --cached --quiet || git commit -m "chore: cron commit $(date -u)"
          git push