name: Cron Commit

on:
  schedule:
    - cron: '0 7 * * *' # runs at 7 AM UTC every day
  workflow_dispatch: # allows manual trigger (optional)

jobs:
  cron-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update file or perform task
        run: |
          echo "hi"