name: Shuttle Deploy

on:
  push:
    branches:
      - "*"
  schedule:
    - cron: "0 0 1 * *" # runs at 00:00 UTC on the 1st of every month
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: proj_01JVV3WRNK7JXAPZVWFG7DJXAQ
